package com.smartstay.tenant.ennum;

public enum NotificationType {

    COMPLAINT_ASSIGN,
    INVOICE_NOTIFICATION,
    COMPLAINT_COMMENTS,

    BED_CHANGE_REQUEST,
    COMPLAINTS_RAISED,
    RAISE_NOTICE_REQUEST,

    MAINTENANCE,
    COMPLAINT,
    CHANGE_BED,
    AMENITY_REQUEST,
    CHECKOUT_REQUEST,
    CHECKOUT_MISSING,
    CHECKIN_MISSING,
    DUE_REMINDERS,
    KYC_REQUEST,
    RECURRING_INVOICE,
    MANUAL_INVOICE,
    INVOICE_GENERATION
}
